### PR TITLE
Only use ES6 modules + lots of refactoring

### PR DESCRIPTION
**Pull request by chaudhuri**
This is a fairly significant update that does many things. Some highlights:

* Transitions to using ES6 modules everywhere. No more `require`s allowed.
* Uses only asynchronous file operations. No more `fs.fooSync()` all over the place, including nested in async functions.
* A bit of refactoring of `initial-vals.ts` to avoid excessive repetition. See the new class `FileBacked` in that module.
* Some refactoring in `utilities.ts` to make all the `isAnnotatedFoo()` functions uniform.
* Lots of minor cleanup and refactoring.

This branch is not very heavily tested, so don't merge this branch yet. This PR is just to keep track of the status of this code refactor.

Files I've still not seriously processed

- [ ] `get.ts`
- [ ] `publish.ts`
- [ ] `lookup.ts`

### CODE REVIEW

**Comment by innofarah** [comment]
I tested the main functionalities and committed some minor fixes. I will do more elaborate testing later but I think it is okay to merge for now (the main functionalities are working).

**Comment by chaudhuri** [comment]
OK, will merge and fastforward.

**Comment by chaudhuri** [comment]
Should (eventually) get rid of the esm branch. Not doing it right away...

**Comment by chaudhuri** [comment]
Getting rid of the `esm` branch now.

**Pull request merged**
